Repository nss-day-cohort-46/rare-server-elusive-elves, pull requests merged in 2021-04, with the labels that each got.

#52 feat: added models
  models/categories.py
  models/comments.py
  models/postReactions.py
  models/posts.py
  models/reaction.py
  models/subscriptions.py
  models/tags.py
  models/users.py
Labels: enhancement

#58 fix: reactions model - file was saved as reaction instead of reactions
  models/__init__.py
  models/reactions.py
  users/request.py
Labels: documentation

#59 feature: get single user
  request_handler.py
  users/__init__.py
  users/request.py
Labels: documentation

#60 feat: check user at login
  rare.session.sql
  request_handler.py
  users/__init__.py
  users/request.py
Labels: documentation

#61 Cc register
  request_handler.py
  users/__init__.py
  users/request.py
Labels: enhancement

#62 feat: added fetch for getting post by user id
  posts/__init__.py
  posts/request.py
  request_handler.py
Labels: bug, enhancement

#63 Cj comments
  comments/__init__.py
  comments/request.py
  kennel.db
  request_handler.py
Labels: documentation, enhancement

#64 Nah categories
  categories/__init__.py
  categories/request.py
  rare.session.sql
  request_handler.py
Labels: documentation, enhancement

#66 Nah tags
  request_handler.py
  tags/__init__.py
  tags/request.py
Labels: documentation, enhancement

#68 Cc post by category
  posts/__init__.py
  posts/request.py
  rare.sql
  request_handler.py
Labels: enhancement

#69 fix: correctly getting post by tag id
  posts/request.py
  rare.sql
Labels: enhancement
